clip: 5
dec_head_dropout: 0.1
dec_trans_layer_num: 2
eval_model_path: ./ModelWeight/unitime.pth
gpu: 0
inference_list: execute_list/inference_Electricity.csv
instruct_path: data_configs/instruct.json
is_training: 0
label_len: 0
learning_rate: 0.0001
lm_ft_type: full
lm_layer_num: 2
lm_pretrain_model: gpt2-small
mask_rate: 0.5
max_backcast_len: 96
max_forecast_len: 720
max_token_num: 14
num_workers: 10
patch_len: 32
patience: 10
seed: 2036
target: OT
train_epochs: 10
training_list: execute_list/train_all.csv
ts_embed_dropout: 0.3
weight_decay: 0
zero_shot_instruct: ''
